import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { VersionToggle } from "@/components/version-toggle";

const geist = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist",
  weight: "100 900",
});

const SITE_URL = process.env.NEXT_PUBLIC_SITE_URL || "https://launchcommand.app";

export const metadata: Metadata = {
  metadataBase: new URL(SITE_URL),
  title: {
    default: "Launch Command — Your entire marketing campaign, from one form",
    template: "%s · Launch Command",
  },
  description:
    "Personas, Meta ads, Google ads, landing pages, and email sequences — generated by AI, consistent across every channel. One form. 60 seconds.",
  keywords: ["AI marketing", "campaign generator", "ad copy generator", "landing page generator", "email sequence AI"],
  openGraph: {
    type: "website",
    url: SITE_URL,
    title: "Your Entire Marketing Campaign. One Form. 60 Seconds.",
    description:
      "AI-generated personas, ads, landing pages, and email sequences — consistent across every channel.",
    siteName: "Launch Command",
  },
  twitter: {
    card: "summary_large_image",
    title: "Launch Command — one form, a full marketing campaign",
    description: "AI-generated ads, landing pages, and email sequences, consistent across every channel.",
  },
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${geist.variable} font-sans antialiased`}>
        <ThemeProvider attribute="class" defaultTheme="dark" enableSystem={false}>
          <VersionToggle />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
