"use client";

import { motion, type Variants } from "framer-motion";
import Link from "next/link";
import { ArrowRight, Sparkles } from "lucide-react";
import { Button } from "@/components/ui/button";
import { NumberTicker } from "./number-ticker";

const fade: Variants = {
  hidden: { opacity: 0, y: 20 },
  show: (i: number) => ({ opacity: 1, y: 0, transition: { delay: i * 0.08, duration: 0.6, ease: "easeOut" } }),
};

export function Hero() {
  return (
    <section className="relative overflow-hidden px-6 pb-24 pt-36 md:pt-44">
      {/* animated gradient beams */}
      <div aria-hidden className="pointer-events-none absolute inset-0 -z-10">
        <div className="absolute left-1/2 top-[-10%] h-[60vh] w-[120vw] -translate-x-1/2 rounded-full bg-[radial-gradient(closest-side,rgba(124,92,255,0.28),transparent)] blur-3xl animate-aurora-drift" />
        <div className="absolute right-[-10%] top-[10%] h-[40vh] w-[40vw] rounded-full bg-[radial-gradient(closest-side,rgba(62,230,219,0.18),transparent)] blur-3xl" />
        <div className="absolute inset-0 bg-grid-pattern [background-size:56px_56px] [mask-image:radial-gradient(ellipse_80%_60%_at_50%_10%,black,transparent_75%)]" />
      </div>

      <div className="container flex flex-col items-center text-center">
        <motion.span
          custom={0}
          variants={fade}
          initial="hidden"
          animate="show"
          className="mb-6 inline-flex items-center gap-2 rounded-full border border-line bg-white/[0.03] px-4 py-1.5 text-xs font-medium tracking-wide text-ink-muted"
        >
          <Sparkles className="h-3.5 w-3.5 text-accent-cyan" />
          One brief in. A full campaign out.
        </motion.span>

        <motion.h1
          custom={1}
          variants={fade}
          initial="hidden"
          animate="show"
          className="max-w-4xl text-balance text-5xl font-bold leading-[0.98] tracking-tight md:text-7xl"
        >
          Your entire marketing campaign.
          <br />
          <span className="grad-text animate-gradient-flow">One form. 60 seconds.</span>
        </motion.h1>

        <motion.p
          custom={2}
          variants={fade}
          initial="hidden"
          animate="show"
          className="mt-7 max-w-2xl text-lg leading-relaxed text-ink-muted"
        >
          Personas, Meta ads, Google ads, landing pages, and email sequences — generated by AI,
          consistent across every channel. You never write a prompt.
        </motion.p>

        <motion.div
          custom={3}
          variants={fade}
          initial="hidden"
          animate="show"
          className="mt-9 flex flex-col items-center gap-3 sm:flex-row"
        >
          <Button asChild size="lg">
            <Link href="/app">
              Generate my campaign free <ArrowRight className="h-4 w-4" />
            </Link>
          </Button>
          <Button asChild variant="ghost" size="lg">
            <Link href="#how">See how it works</Link>
          </Button>
        </motion.div>
        <motion.p custom={4} variants={fade} initial="hidden" animate="show" className="mt-4 font-mono text-xs uppercase tracking-widest text-accent-cyan">
          Free plan · no card required
        </motion.p>

        <motion.dl
          custom={5}
          variants={fade}
          initial="hidden"
          animate="show"
          className="mt-16 grid w-full max-w-3xl grid-cols-2 gap-8 border-t border-line pt-8 md:grid-cols-4"
        >
          {[
            { v: 12000, suffix: "+", label: "campaigns generated" },
            { v: 5, label: "assets per brief" },
            { v: 60, suffix: "s", label: "brief to first draft" },
            { v: 0, label: "prompts to write" },
          ].map((s, i) => (
            <div key={i}>
              <dd className="text-3xl font-bold tracking-tight text-ink">
                <NumberTicker value={s.v} suffix={s.suffix} />
              </dd>
              <dt className="mt-1 font-mono text-[10px] uppercase tracking-widest text-ink-faint">{s.label}</dt>
            </div>
          ))}
        </motion.dl>
      </div>
    </section>
  );
}
